# -*- coding: utf-8 -*-
# Writes src/config/mqtt_node_config.h from the NODE_ID environment variable.
#
# This id is only the FALLBACK label, used by the direct-to-Lambda transport
# (GATEWAY_USE_MQTT=0), which has no registration handshake. Over MQTT the Fog
# gateway assigns the real node id and the firmware stores it in NVS.
#
#   NODE_ID=bench-7a pio run          (PowerShell: $env:NODE_ID = "bench-7a")
Import("env")  # type: ignore[name-defined]  # noqa: F821

import os
from os.path import join


def c_escape(s):
    if s is None:
        return ""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


out_path = join(env["PROJECT_DIR"], "src", "config", "mqtt_node_config.h")  # type: ignore[name-defined]
node_id = c_escape(os.environ.get("NODE_ID", "001"))

content = f"""#pragma once
// Generated by scripts/mqtt_node_env.py — set NODE_ID before build, or edit default below.
#define MQTT_NODE_ID "{node_id}"
"""

os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)

print(f"[mqtt_node_env] Wrote {out_path} NODE_ID={node_id!r}")
